detecting the colouriser

diff --git a/comsys/branches/comsys.mk5/subarchitectures/comsys/abduction/abduct b/comsys/branches/comsys.mk5/subarchitectures/comsys/abduction/abduct
--- a/comsys/branches/comsys.mk5/subarchitectures/comsys/abduction/abduct
+++ b/comsys/branches/comsys.mk5/subarchitectures/comsys/abduction/abduct
@@ -1,3 +1,10 @@
 #!/bin/sh
 
-cat | ./test_abduction "$@" 2>&1 | grcat ./grc
+COLOURIZER=cat
+
+# test presence of grcat
+# (can't use `where' as it's not a sh builtin)
+grcat >/dev/null 2>&1  # return code is 1 when grcat present
+if [ $? -eq 1 ]; then COLOURIZER="grcat ./grc"; fi
+
+./test_abduction "$@" 2>&1 | $COLOURIZER
